### ISSUE TITLE
Cannot Run Locally - Broken Dependency?

### ISSUE THREAD

**Issue by bpod** [joshghent/password#23]
Cannot run locally. Tried a fresh build off of both master and develop with the same result. I thought maybe it was my node/npm version(s) but tried with multiple versions with the same results... Some kind of issue with `rollbar.js`. 🤷‍♂️ 

Tried Versions
- `node 10.8.0` + `npm 6.2.0`
- `node 8.11.3` + `npm 5.6.0`
- `node 8.1.3` + `npm 5.0.3`

**Error**
```
/node_modules/rollbar/src/server/rollbar.js:24
  if (options.minimumLevel !== undefined) {
              ^

TypeError: Cannot read property 'minimumLevel' of undefined
    at new Rollbar (/Users/burtonp/workspaces/xkcd-password-generator/node_modules/rollbar/src/server/rollbar.js:24:15)
    at Object.<anonymous> (/Users/burtonp/workspaces/xkcd-password-generator/server.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! password@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the password@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/burtonp/.npm/_logs/2018-10-02T15_57_40_791Z-debug.log
```

**Comment by joshghent** [comment]
Huh that's interesting. Maybe we can remove rollbar for now, as it's causing a few issues. You are working on the site recreation in react so let's get that working then we can put rollbar back in.

**Comment by bpod** [comment]
Sounds good. I'll let you know if I run into any other issues. Can you assign #21 to me so no one else picks it up? 😎

**Comment by bpod** [comment]
Closing to address in my React Branch

**Comment by joshghent** [comment]
@bpod Thanks 🎉
